spring:
  application:
    name: URLShortner
  datasource:
    url: jdbc:mysql://localhost:3306/URLShortner
    username: root
    password: asdfasdf
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect